/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtistList: typeof import('./src/components/search/ArtistList.vue')['default']
    BackgroundImageController: typeof import('./src/components/misc/BackgroundImageController.vue')['default']
    CalcChart: typeof import('./src/components/CalcChart.vue')['default']
    Calculator: typeof import('./src/components/song/Calculator.vue')['default']
    Comment: typeof import('./src/components/user/Comment.vue')['default']
    CommentAction: typeof import('./src/components/user/CommentAction.vue')['default']
    CommentFrame: typeof import('./src/components/user/CommentFrame.vue')['default']
    CommentInput: typeof import('./src/components/user/CommentInput.vue')['default']
    CommentLikeButton: typeof import('./src/components/user/CommentLikeButton.vue')['default']
    CommentList: typeof import('./src/components/user/CommentList.vue')['default']
    CommentReplyButton: typeof import('./src/components/user/CommentReplyButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    HeaderDrawer: typeof import('./src/components/header/HeaderDrawer.vue')['default']
    HeaderMenu: typeof import('./src/components/header/HeaderMenu.vue')['default']
    InfoItem: typeof import('./src/components/board/InfoItem.vue')['default']
    ListItem: typeof import('./src/components/board/ListItem.vue')['default']
    LoginCard: typeof import('./src/components/user/LoginCard.vue')['default']
    MarkingCard: typeof import('./src/components/song/MarkingCard.vue')['default']
    MarkingTags: typeof import('./src/components/song/MarkingTags.vue')['default']
    NoticeBoard: typeof import('./src/components/NoticeBoard.vue')['default']
    PoolCard: typeof import('./src/components/PoolCard.vue')['default']
    RankChange: typeof import('./src/components/board/RankChange.vue')['default']
    RankChangeSpan: typeof import('./src/components/board/RankChangeSpan.vue')['default']
    RankingCalendar: typeof import('./src/components/RankingCalendar.vue')['default']
    RankingCard: typeof import('./src/components/board/RankingCard.vue')['default']
    RankingCardMobile: typeof import('./src/components/board/RankingCardMobile.vue')['default']
    RankingDialog: typeof import('./src/components/board/RankingDialog.vue')['default']
    RankItem: typeof import('./src/components/board/RankItem.vue')['default']
    RankItemMobile: typeof import('./src/components/board/RankItemMobile.vue')['default']
    RegisterCard: typeof import('./src/components/user/RegisterCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./src/components/misc/ScrollToTop.vue')['default']
    SearchArtist: typeof import('./src/components/search/SearchArtist.vue')['default']
    SearchArtistBlocks: typeof import('./src/components/search/SearchArtistBlocks.vue')['default']
    SearchMusicCard: typeof import('./src/components/search/SearchMusicCard.vue')['default']
    SearchMusicCards: typeof import('./src/components/search/SearchMusicCards.vue')['default']
    SearchSongTable: typeof import('./src/components/search/SearchSongTable.vue')['default']
    SideAdvertisement: typeof import('./src/components/misc/SideAdvertisement.vue')['default']
    SongHistoryTable: typeof import('./src/components/song/SongHistoryTable.vue')['default']
    SongInfo: typeof import('./src/components/song/SongInfo.vue')['default']
    SpecialSelector: typeof import('./src/components/board/SpecialSelector.vue')['default']
    VideoInfo: typeof import('./src/components/song/VideoInfo.vue')['default']
    VideoStat: typeof import('./src/components/song/VideoStat.vue')['default']
  }
}
