/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtistList: typeof import('./src/components/ArtistList.vue')['default']
    BackgroundImageController: typeof import('./src/components/BackgroundImageController.vue')['default']
    CalcChart: typeof import('./src/components/CalcChart.vue')['default']
    Calculator: typeof import('./src/components/Calculator.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderDrawer: typeof import('./src/components/HeaderDrawer.vue')['default']
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default']
    InfoItem: typeof import('./src/components/InfoItem.vue')['default']
    LoginCard: typeof import('./src/components/LoginCard.vue')['default']
    PoolCard: typeof import('./src/components/PoolCard.vue')['default']
    RankChange: typeof import('./src/components/RankChange.vue')['default']
    RankingCalendar: typeof import('./src/components/RankingCalendar.vue')['default']
    RankingCard: typeof import('./src/components/RankingCard.vue')['default']
    RegisterCard: typeof import('./src/components/RegisterCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./src/components/ScrollToTop.vue')['default']
    SearchArtist: typeof import('./src/components/SearchArtist.vue')['default']
    SearchArtistBlocks: typeof import('./src/components/SearchArtistBlocks.vue')['default']
    SearchSongTable: typeof import('./src/components/SearchSongTable.vue')['default']
    SideAdvertisement: typeof import('./src/components/SideAdvertisement.vue')['default']
    SongHistoryTable: typeof import('./src/components/SongHistoryTable.vue')['default']
    SongInfo: typeof import('./src/components/SongInfo.vue')['default']
    SpecialSelector: typeof import('./src/components/SpecialSelector.vue')['default']
    VideoInfo: typeof import('./src/components/VideoInfo.vue')['default']
    VideoStat: typeof import('./src/components/VideoStat.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
